- name: ec2 instance build in aws
  amazon.aws.ec2_instance:
    instance_type: "{{ instance_type }}"
    region: "{{ region }}"
    image_id: "{{ image }}"
    security_groups: "{{ sg_id }}"
    tags: "{{ backend_tags if (item in backend_instances) else db_tags }}"
    wait: true
    wait_timeout: 300
    state: present
  loop: "{{ backend_instances + db_instances }}"
  register: ec2_instance_output
  when:
    - action == "create"

- name: ec2 instances display output
  ansible.builtin.debug:
    msg: |
      "name: {{ item.item }}"
      "private_ip: {{ item.instances[0].private_ip_address }}"
      "public_ip: {{ item.instances[0].public_ip_address }}"
  loop: "{{ ec2_instance_output }}"
  when: 
    - action == "create"